# Generated by Django 5.1.2 on 2024-12-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('sports', 'Sports'), ('food', 'Food'), ('gaming', 'Gaming'), ('politics', 'Politics'), ('fitness', 'Fitness'), ('medical', 'Medical'), ('nature', 'Nature'), ('technology', 'Technology'), ('other', 'Other')], default='None', max_length=255),
        ),
    ]
